# -*- coding: utf-8 -*-
"""instructormapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13AOUgwkeDS0NW7p6Ei0tbUfKD6b15dvI
"""

# instructor_mapping.py
# Clearly defined instructor contact details

INSTRUCTOR_EMAILS = {
    "John Doe": "john.doe@example.com",
    "Jane Smith": "jane.smith@example.com",
    "Vivian Scott":"vscott@schoolofrock.com",
    "Hugh Scott":"huscott@schoolofrock.com",
    "Zach Jones":"earthwindfile6@gmail.com",
    "Matt Mireles":"mwmireles@gmail.com",
    "Gio Soto":"davidgiosoto@gmail.com",
    "Daniel Rutledge":"drutledge@schoolofrock.com",
    "Andre Cunningham":"apcunningham2@gmail.com",
    "Noel Rodriguez":"noel.rdz.g@gmail.com",
    "Logan Gill":"lgill57851@gmail.com",
    "Rodney Chinelliott":"elrodney@gmail.com",
    "Quincy Cotton":"qjcmusic@gmail.com",
    "Richard Sharp":"rsharp@schoolofrock.com",
    "Bennett Sharp":"bsharp@schoolofrock.com",
    "Reef Stallworth":"sonto456@gmail.com",
    "Brodie Scott":"bonniescott987@gmail.com",
    "Camille McCloskey":"camillemccloskey@gmail.com",
    "Julie Harvley":"julienaugie@gmail.com"
    # Add more instructors here clearly
}

# Optional (if you plan to implement SMS via Twilio)
INSTRUCTOR_PHONES = {
    "John Doe": "+18323359429",
    "Jane Smith": "+18321234567",
    # Add more instructors here clearly
}

def get_instructor_email(name):
    email = INSTRUCTOR_EMAILS.get(name)
    if email:
        return email
    else:
        print(f"⚠️ Email not found clearly for instructor: {name}")
        return None