# -*- coding: utf-8 -*-
"""NotesReminder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mkqCxWHyjvRR9Ldofl5vzbtV4xMAtc8K
"""

import sqlite3

# Connect to SQLite database (creates the database file if it doesn't exist clearly)
conn = sqlite3.connect('reminders.db')

# Create a cursor to execute SQL commands clearly
cursor = conn.cursor()

# Define your reminders table clearly
cursor.execute('''
CREATE TABLE IF NOT EXISTS reminders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    lesson_id TEXT UNIQUE,
    school TEXT,
    instructor_name TEXT,
    lesson_date TEXT,
    lesson_time TEXT,
    lesson_type TEXT,
    students TEXT,
    location TEXT,
    reminder_sent INTEGER DEFAULT 0,
    reminder_count INTEGER DEFAULT 0,
    note_completed INTEGER DEFAULT 0,
    attendance_status TEXT DEFAULT 'unknown',
    last_checked DATE,
    last_reminder_sent TIMESTAMP
);
''')

# Commit changes and close clearly
conn.commit()
conn.close()

print("📂 SQLite database and 'reminders' table created successfully!")

#code to check that this is a valid table
""" Verify table structure
conn = sqlite3.connect('reminders.db')
cursor = conn.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

print("📋 Tables in your database clearly:", tables)

cursor.execute("PRAGMA table_info(reminders);")
columns = cursor.fetchall()

print("\n🔍 Clearly checking 'reminders' table structure:")
for col in columns:
    print(col)

conn.close()"""
