name: Daily Notes Reminder

on:
  schedule:
    - cron: '0 8 * * *'  # Every day at 8am UTC
  workflow_dispatch:

jobs:
  run-westu:
    name: Run for West U
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv boto3
          python -m playwright install --with-deps chromium
      
      - name: Create screenshots directory
        run: mkdir -p screenshots
      
      - name: Run notes reminder for West U
        run: |
          python run_daily.py --school westu-sor
        continue-on-error: true
      
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: westu-screenshots
          path: |
            screenshots/*.png
            screenshots/trace.zip
      
      - name: Upload error logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: westu-logs
          path: |
            *.log
            westu-sor_lessons_*.csv

  run-theheights:
    name: Run for The Heights
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv boto3
          python -m playwright install --with-deps chromium
      
      - name: Create screenshots directory
        run: mkdir -p screenshots
      
      - name: Run notes reminder for The Heights
        run: |
          python run_daily.py --school theheights-sor
        continue-on-error: true
      
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: theheights-screenshots
          path: |
            screenshots/*.png
            screenshots/trace.zip
      
      - name: Upload error logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: theheights-logs
          path: |
            *.log
            theheights-sor_lessons_*.csv
